# Generated by Django 4.0.5 on 2022-06-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=100)),
                ('DateOfEvent', models.DateField()),
                ('TimeOfEvent', models.TimeField()),
            ],
        ),
    ]
